//THIS IS THE JAVASCRIPT FOR THE RESOURCES PAGE

//AN ARRAY OF TERMS AND DEFINITIONS AND MAYBE IMAGES TO DRAW FROM?



//ON-CLICK EVENT LISTENERS FOR THE TERMS ON THE LEFT SIDE MENU



//ARE THE RESOURCES WE LIST GOING TO BE HREFS?